version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # Official Jenkins LTS with Java 17
    container_name: jenkins
    restart: unless-stopped
    ports:
      - '8080:8080'  # Web UI
      # - '50000:50000'  # Agent communication
    volumes:
      - jenkins_data:/var/jenkins_home  # Persistent storage
      - /var/run/docker.sock:/var/run/docker.sock  # For Docker integration (optional)
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  # Skip setup wizard if pre-configured
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}  # Set in .env file
    networks:
      - jenkins-net

volumes:
  jenkins_data:  # Named volume for persistence
